version: '2.4'
services:
  webserver:
    image: feedback-tool-dev-frontend:latest
    volumes:
      - ../../frontend/src:/opt/app-root/src/src
    ports:
      - "4200:4200"
    networks:
      - web
    depends_on:
      - webapp
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:4200"]
      interval: 5s
      timeout: 5s
      retries: 3
    logging:
      driver: "none"
  webapp:
    image: feedback-tool-app:latest
    networks:
      - web
      - db
      - ldap
    volumes:
      - ../../:/opt/app-root/src
    depends_on:
      db:
        condition: service_healthy
      ldap:
        condition: service_healthy
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -c \"select 'OK';\""]
      interval: 5s
      timeout: 5s
      retries: 3
    logging:
      driver: "none"
  ldap:
    image: osixia/openldap:latest
    volumes:
      - ../shared/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    networks:
      - ldap
    ports:
      - "389:389"
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D \"cn=admin,dc=example,dc=org\" -w admin"]
      interval: 5s
      timeout: 5s
      retries: 3
    command: --copy-service
  ldap-ui:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
      - "6443:443"
    networks:
      - ldap
    depends_on:
      - ldap
    logging:
      driver: "none"

networks:
  ldap:
  web:
  db:


