from tests.integration import constants

DEFAULT_TEST_SETTINGS = {
    "adaero.test_mode": True,
    "ahl.web.debug_all": True,
    "adaero.use_local_sqlite3": True,
    "adaero.company_name": "Example Org.",
    "adaero.business_unit": "Alpha",
    "adaero.homebase_location": "London",
    "adaero.production_hostname": constants.TEST_PRODUCTION_HOSTNAME,
    "adaero.production_user": constants.TEST_PRODUCTION_USER,
    "adaero.served_on_https": True,
    "adaero.talent_manager_usernames": '["llovelace"]',
    "adaero.load_talent_managers_on_app_start": False,
    "adaero.staff_override_usernames": None,
    "adaero.support_email": "support@example.org",
    "adaero.reply_email": "no-reply@example.org",
    "adaero.ldap_uri": "ldap://localhost:9999",
    "adaero.ldap_user_bind_template": "{username}@localhost.test",
    "adaero.ldap_search_bind_dn": "admin",
    "adaero.ldap_search_password": "admin_pw",
    "adaero.ldap_username_key": constants.TEST_USERNAME_KEY,
    "adaero.ldap_manager_key": constants.TEST_MANAGER_KEY,
    "adaero.ldap_location_key": constants.TEST_LOCATION_KEY,
    "adaero.ldap_uid_key": constants.TEST_UID_KEY,
    "adaero.ldap_department_key": constants.TEST_DEPARTMENT_KEY,
    "adaero.ldap_business_unit_key": constants.TEST_BUSINESS_UNIT_KEY,
    "adaero.ldap_base_dn": "O=foo",
    "adaero.ldap_dn_username_attribute": "cn",
    "adaero.ldap_dn_username_regex": r"CN=([\w\s\\\,\(\)]*),OU=",
    "adaero.enable_send_email": True,
    "beaker.session.type": "memory",
    "beaker.session.secret": "secret",
    "rest_toolkit.debug": True,
}
