from tests.integration import constants

DEFAULT_TEST_SETTINGS = {
    "ahl.web.debug_all": True,
    "feedback_tool.use_local_sqlite3": True,
    "feedback_tool.company_name": "Example Org.",
    "feedback_tool.business_unit": "Alpha",
    "feedback_tool.homebase_location": "London",
    "feedback_tool.production_hostname": constants.TEST_PRODUCTION_HOSTNAME,
    "feedback_tool.production_user": constants.TEST_PRODUCTION_USER,
    "feedback_tool.served_on_https": True,
    "feedback_tool.talent_manager_usernames": '["llovelace"]',
    "feedback_tool.reload_users_on_app_start": False,
    "feedback_tool.load_talent_managers_on_app_start": False,
    "feedback_tool.staff_override_usernames": None,
    "feedback_tool.support_email": "support@example.org",
    "feedback_tool.reply_email": "no-reply@example.org",
    "feedback_tool.ldap_uri": "ldap://localhost:9999",
    "feedback_tool.ldap_user_bind_template": "{username}@localhost.test",
    "feedback_tool.ldap_search_bind_dn": "admin",
    "feedback_tool.ldap_search_password": "admin_pw",
    "feedback_tool.ldap_username_key": constants.TEST_USERNAME_KEY,
    "feedback_tool.ldap_manager_key": constants.TEST_MANAGER_KEY,
    "feedback_tool.ldap_location_key": constants.TEST_LOCATION_KEY,
    "feedback_tool.ldap_uid_key": constants.TEST_UID_KEY,
    "feedback_tool.ldap_department_key": constants.TEST_DEPARTMENT_KEY,
    "feedback_tool.ldap_business_unit_key": constants.TEST_BUSINESS_UNIT_KEY,
    "feedback_tool.ldap_base_dn": "O=foo",
    "feedback_tool.ldap_dn_username_attribute": "cn",
    "feedback_tool.ldap_dn_username_regex": r"CN=([\w\s\\\,\(\)]*),OU=",
    "feedback_tool.enable_send_email": True,
    "beaker.session.type": "memory",
    "beaker.session.secret": "secret",
    "rest_toolkit.debug": True,
}
